trigger:
- main
- master

variables:
  imageRepository: saurabhdhande/bird
  dockerfilePath: $(Build.SourcesDirectory)/Dockerfile
  buildContext: $(Build.SourcesDirectory)
  dockerRegistryServiceConnection: Dockerhub
  majorVersion: 1
  minorVersion: 0

pool:
  vmImage: Ubuntu-latest

stages:
- stage: DockerBuildPush
  displayName: Docker build and push
  jobs:
  - job: build
    displayName: Docker build
    steps:



    - task: Docker@2
      displayName: Docker build and push
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        buildContext: $(buildContext)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: $(majorVersion).$(minorVersion).$(Build.BuildId)
