trigger:
- main
- master

variables:
  imageRepository: saurabhdhande/bird
  dockerfilePath: $(Build.SourcesDirectory)/Dockerfile
  buildContext: $(Build.SourcesDirectory)

  dockerRegistryServiceConnection: Dockerhub
  tag: $(Build.BuildId)
pool:
  name: Ubuntu
  demands:
    - agent.name -equals ubuntu-self

stages:
- stage: DockerBuildPush
  displayName: Docker build and push
  jobs:
  - job: build
    displayName: Docker build
    steps:
    - task: PowerShell@2
      displayName: Read Docker image version
      inputs:
        targetType: inline
        pwsh: true
        script: |
          $version = Get-Content "$(Build.SourcesDirectory)/version.json" -Raw | ConvertFrom-Json
          $imageTag = "$($version.MajorVersion).$($version.MinorVersion).$(Build.BuildId)"

          Write-Host "Docker image tag: $imageTag"
          Write-Host "##vso[task.setvariable variable=imageTag]$imageTag"

    - task: Docker@2
      displayName: Docker build and push
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        buildContext: $(buildContext)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(imageTag)
